"""Constants for the neoom BEAAM integration."""

DOMAIN = "neoom_beaam"

# Config keys
CONF_HOST = "host"
CONF_API_KEY = "api_key"
CONF_SCAN_INTERVAL = "scan_interval"

DEFAULT_SCAN_INTERVAL = 10  # seconds
DEFAULT_PORT = 80

# API endpoints
API_BASE = "http://{host}/api/v1"
API_SITE_STATE = "/site/state"
API_SITE_CONFIG = "/site/configuration"
API_THING_STATES = "/things/{thing_id}/states"
API_THING_COMMANDS = "/things/{thing_id}/commands"
API_THING_STATES_SET = "/things/{thing_id}/states"

# DataPoint keys from energyFlow/states (site/state)
DP_POWER_PRODUCTION = "POWER_PRODUCTION"
DP_POWER_CONSUMPTION_CALC = "POWER_CONSUMPTION_CALC"
DP_POWER_GRID = "POWER_GRID"
DP_POWER_STORAGE = "POWER_STORAGE"
DP_STATE_OF_CHARGE = "STATE_OF_CHARGE"
DP_SELF_SUFFICIENCY = "SELF_SUFFICIENCY"
DP_ENERGY_PRODUCED = "ENERGY_PRODUCED"
DP_ENERGY_CONSUMED_CALC = "ENERGY_CONSUMED_CALC"
DP_ENERGY_IMPORTED = "ENERGY_IMPORTED"
DP_ENERGY_EXPORTED = "ENERGY_EXPORTED"
DP_ENERGY_CHARGED = "ENERGY_CHARGED"
DP_ENERGY_DISCHARGED = "ENERGY_DISCHARGED"

# Thing-level DataPoint keys (things/{id}/states)
DP_CONNECTION = "CONNECTION"
DP_VOLTAGE_P1 = "VOLTAGE_P1"
DP_VOLTAGE_P2 = "VOLTAGE_P2"
DP_VOLTAGE_P3 = "VOLTAGE_P3"
DP_FREQUENCY = "FREQUENCY"
DP_ACTIVE_POWER = "ACTIVE_POWER"
DP_SOC = "SOC"
DP_REACTIVE_POWER = "REACTIVE_POWER"
DP_APPARENT_POWER = "APPARENT_POWER"
DP_CURRENT_P1 = "CURRENT_P1"
DP_CURRENT_P2 = "CURRENT_P2"
DP_CURRENT_P3 = "CURRENT_P3"

# Thing types
THING_TYPE_INVERTER = "INVERTER"
THING_TYPE_BATTERY = "BATTERY"
THING_TYPE_GRID_METER = "GRID_METER"
THING_TYPE_PV = "PV"
THING_TYPE_EV_CHARGER = "EV_CHARGER"

# Coordinator keys
COORDINATOR_SITE = "site"
COORDINATOR_THINGS = "things"
